@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Bob --> Cat: Can you help
Cat --> Bob : let me check

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml